### ISSUE TITLE
Can I use cuda to speed up the training process?

### ISSUE THREAD

**Issue by Hao-Yuan-He** [ML-KULeuven/deepproblog#11]
I'm wondering if I can use Cuda to speed up the training process, the example/MNIST/addition.py seems to only use CPU.

**Comment by rmanhaeve** [comment]
Hi

You can put the neural networks behind the neural predicate on the GPU to accelerate these by callign the .cuda(device) method. The other parts of the inference cannot be accelerated.

Kind regards,
Robin
