### ISSUE TITLE
How to wrote prolog programming for Classification & Regression Task

### ISSUE THREAD

**Issue by GlitchofMatrix** [ML-KULeuven/deepproblog#8]
I saw your examples and it was very clear.
But, I am new to Prolog.
I need an example for binary classification, multiclass, multilabel classification, regression tasks.
Thanks in advance

**Comment by rmanhaeve** [comment]
Hi

The addition example is multiclass classification. The coins example is binary classification.  Regression tasks are not possible in DeepProbLog currently. What exactly would you want to do w.r.t. multilabel classification?

**Comment by GlitchofMatrix** [comment]
Yes. Multilabel multiclass classification

**Comment by rmanhaeve** [comment]
You can introduce separate predicates for each of the labels. They are not necessarily mutually exclusive, so you are automatically in the multi-label setting.
